MONGOHOST: "arctrdcn018"
DBNAME: "wirehead_benchmark_multigpu_gen"
SWAP_CAP: 100

# Change if you know what you're doing
SAMPLE: ["data", "label"]
WRITE_COLLECTION: "write"
READ_COLLECTION: "read"
COUNTER_COLLECTION: "counter"
TEMP_COLLECTION: "temp"
CHUNKSIZE: 10
