MONGOHOST: "localhost" # replace with the ip/hostname of your mongonode
DBNAME: "synthseg-example"
SWAP_CAP: 2

SAMPLE: ["data", "label"]
WRITE_COLLECTION: "write"
READ_COLLECTION: "read"
COUNTER_COLLECTION: "counter"
TEMP_COLLECTION: "temp"
CHUNKSIZE: 10
