# mongod.conf

# Where and how to store data.
storage:
  dbPath: /usr/local/var/mongodb
  journal:
    enabled: true

# Where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /usr/local/var/log/mongodb/mongo.log

# Network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

# Replication settings
replication:
  replSetName: "rs0"

# Operational settings
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
