MONGOHOST: "arctrdcn018.rs.gsu.edu"
DBNAME: "wirehead_benchmark_wirehead_train"
SWAP_CAP: 10

# Change if you know what you're doing
SAMPLE: ["data", "label"]
WRITE_COLLECTION: "write"
READ_COLLECTION: "read"
COUNTER_COLLECTION: "counter"
TEMP_COLLECTION: "temp"
CHUNKSIZE: 10
